In [1]:
import numpy as np

In [2]:
# Matrix in numpy
a = np.array([[1,2],
              [3,4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
# Addition of matrices
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(a + b)

[[ 6  8]
 [10 12]]


In [8]:
# Multiplication of matrices 
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.dot(a, b))
#Shorthand method for multiplication
a @ b     

[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [9]:
# Transpose of matrix
a = np.array([[1,2,3],
              [4,5,6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
# Use Seed for ML experiments
np.random.seed(3)
np.random.rand(3)

array([0.5507979 , 0.70814782, 0.29090474])

In [11]:
# Save array like .npy file
a = np.array([1,2,3,4])
np.save("data.npy",a)

In [12]:
# Load array
a = np.load("data.npy")
print(a)

[1 2 3 4]


In [13]:
# To find no. of dimensions
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
arr

2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# To access a single element 
print(arr[1,2]) 

6


In [15]:
# To access complete row
print(arr[1]) 

[4 5 6]


In [16]:
# To access complete column
arr[:,1] 

array([2, 5, 8])

In [17]:
# For whole matrix
arr[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Slicing: 
# Syntax: arr[row_start:row_end, col_start:col_end]
arr[0:2, 1:3] 

array([[2, 3],
       [5, 6]])

In [19]:
#Logical Selection (Filtering)
arr = np.array([10,20,30,40])
arr > 20

array([False, False,  True,  True])

In [20]:
arr[arr % 20 == 0]

array([20, 40])

In [21]:
# Broadcasting
arr = np.array([1,2,3])
arr + 5

array([6, 7, 8])

In [22]:
# 2D Broadcasting
arr = np.array([[1,2,3],
                [4,5,6]])
arr + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])