In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
arr = np.array([1, 2, 3])
arr
print(arr.dtype)

int64


In [4]:
# Type casting (Convert one datatype into other)
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


In [5]:
arr = np.array([1.5, 2.9, 3.2])
arr = arr.astype(int)
print(arr)

[1 2 3]


In [7]:
# Arithematic operations on array 
a = np.array([10,20,30])
b = np.array([1,2,3])
a+b

array([11, 22, 33])

In [8]:
a-b

array([ 9, 18, 27])

In [9]:
a*b

array([10, 40, 90])

In [10]:
a/b

array([10., 10., 10.])

In [11]:
a**2

array([100, 400, 900])

In [12]:
# Scalar operations (This function use Broadcasting)
a + 5

array([15, 25, 35])

In [13]:
# Universal Functions (ufuncs)
arr = np.array([1,4,9,16])
np.sqrt(arr)

array([1., 2., 3., 4.])

In [14]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [15]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])