In [1]:
import numpy as np
import pandas as pd

In [3]:
#Creating numpy array
a = [1,2,3,4]    #List
b = np.array(a)
b

array([1, 2, 3, 4])

In [4]:
type(b)      #To find dataType

numpy.ndarray

In [7]:
#Array through built-in methods
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.arange(0, 8, 4)

array([0, 4])

In [10]:
np.linspace(1, 10, 8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [11]:
np.empty(10)

array([1.14750819e-311, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 4.18487917e-062, 1.74254808e-076, 5.20650868e-090,
       8.01021197e+165, 4.49233919e-315])

In [13]:
np.random.seed()   # Seed: Set the values,So everytime fixed  random values generate
num = np.random.rand(4)   
print(num)

[0.7566332  0.48475041 0.77541141 0.42590136]


In [15]:
np.random.randn(3)     # Generate random numbers close to zero

array([ 0.31695581, -0.11521785,  1.21227354])

In [16]:
np.random.randint(4,12,8)      # Write min,max and number of elements

array([ 6,  4, 11,  9, 11,  5,  9, 10], dtype=int32)

In [18]:
# How to create 1D array 
a = [1,2,3,4] 
b = np.array(a)
print(b.ndim)       #Print number of dimensions
b

1


array([1, 2, 3, 4])

In [19]:
# How to create 2D array
x = [[1,2,3,4],[5,6,7,8]] 
y = np.array(x)
print(y.ndim)
y

2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
y.shape       # To find the no. of rows and column

(2, 4)

In [24]:
y.dtype      #To find the data type of elements

dtype('int64')

In [25]:
y.size       # Total no. of elements

8

In [26]:
y.max()      # To find maximum value

np.int64(8)

In [27]:
y.min()     # To find minimum value

np.int64(1)

In [33]:
y.argmax()  # Max value index 

np.int64(7)

In [34]:
y.argmin()  # Min value index

np.int64(0)

In [35]:
y.reshape(4, 2)    # Reshape the no. of rows with column

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.append(a, 4)     # Element add at last of array a

array([1, 2, 3, 4, 4])

In [37]:
np.insert(a, 3, 10)       # Add value at index 3 in array a

array([ 1,  2,  3, 10,  4])

In [39]:
np.sort(a)

array([1, 2, 3, 4])

In [40]:
np.delete(a, 2)    # Remove value at index 2 in array a

array([1, 2, 4])

In [41]:
#  Concatenate (Combining Arrays)
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [42]:
# Splitting Arrays
arr = np.array([1,2,3,4,5,6])
np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]